services:
  api:
    build: .
    ports:
       - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - spring-mysql-network

networks:
  spring-mysql-network: